---

# Boxed installation playbook
# ---------------------------

# A Simple, straight playbook for producing
# a boxed installation in a vagrant VM.


- name: 'StatsD boxed installation'

  hosts: vagrant

  pre_tasks:

    - name: APT update
      become: yes
      when: ansible_os_family == 'Debian'
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Node.js
      become: yes
      when: ansible_os_family == 'Debian'
      apt: "name={{item}} state=installed"
      with_items:
        - nodejs-legacy
        - npm

  vars:
    # Configure your StatsD here
    statsd_address: 0.0.0.0
    statsd_mgmt_address: 0.0.0.0
    statsd_graphite_host:
    statsd_graphite_port:

  roles:
    - '.'    # This role itself

