---

- name: Create user and group for StatsD
  become: yes
  user:
    createhome: no
    name: "{{statsd_user}}"
  tags:
    - conf
    - statsd
    - monitoring

- name: Create StatsD directories
  become: yes
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - "{{statsd_conf_dir}}"
    - "{{statsd_run_dir}}"
    - "{{statsd_log_dir}}"
  tags:
    - conf
    - statsd
    - monitoring

- name: Create StatsD init script
  become: yes
  template:
    src: "{{item}}"
    dest: "{{statsd_init_script}}"
    mode: 0755
  with_first_found:
    - files:
        - "init.{{ansible_distribution}}-{{ansible_distribution_release}}"
        - "init.{{ansible_distribution}}"
        - "init.{{ansible_os_family}}"
      paths:
        - ../templates/
      skip: true
  tags:
    - init
    - conf
    - statsd
    - monitoring
