---

- include: configure-source.yml
  when: statsd_install_from_source

- name: Configure StatsD
  become: yes
  template:
    src: config.js
    dest: "{{statsd_conf_file}}"
  notify: restart statsd
  tags:
    - conf
    - statsd
    - monitoring

- name: Add StatsD to init
  become: yes
  service:
    name: "{{statsd_service_name}}"
    enabled: yes
  tags:
    - init
    - conf
    - statsd
    - monitoring
